name: GeoHammer build for MS Windows
on: [push, workflow_dispatch]
jobs:
  GeoHammer-Windows-Build:
    runs-on: windows-latest
    steps:
      - name: Check out repository code
        uses: actions/checkout@v4
      - name: Set JDK 21
        uses: actions/setup-java@v4
        with:
          java-version: '21'
          distribution: 'liberica'
          java-package: 'jdk+fx'
          architecture: 'x64'
      - name: Cache local Maven repository
        uses: actions/cache@v4
        with:
          path: ~/.m2/repository
          key: ${{ runner.os }}-maven-${{ hashFiles('**/pom.xml') }}
          restore-keys: |
            ${{ runner.os }}-maven-    
      - name: Build with Maven
        run: mvn --batch-mode install -P windows-build
      - name: Package
        run: jpackage --input target\ --name geohammer --main-jar geohammer.jar --main-class com.ugcs.gprvisualizer.app.MainGeoHammer --type app-image --runtime-image target\jre21
      - name: Staging artifacts
        run: mkdir staging && copy target\*.zip staging && copy *.msi staging
      - name: Store artifacts
        uses: actions/upload-artifact@v4
        with:
          name: Windows-Package
          path: staging
          retention-days: 5
